### ISSUE TITLE
Add support for CSV files

### ISSUE THREAD

**Issue by aravindvnair99** [DSC-ASEB/Weekly-Shuffle-Partner-Generator#4]
- XLSX files work now, but CSV is also a popular format.
- Should add CSV support for input as output is CSV anyway.
- So ideally, the input should be CSV or XLSX.

**Comment by aravindvnair99** [comment]
> Branch [issue-4-Add_support_for_CSV_files](https://github.com/DSC-ASEB/Weekly-Shuffle-Partner-Generator/tree/issue-4-Add_support_for_CSV_files) created!

@SaiNikhileshReddy Use this branch for adding CSV input support

**Comment by sainikhileshreddy** [comment]
@aravindvnair99, I have taken up this issue. 

I have few cases in mind on how to do CLI interface.

Scenario:
1) Like old way send the XLSX files
2) We can ask user to create a special directory for all the CSV files
    like: ```python run.py assets``` # here assets will store pre-defined file names. db.csv, ws.csv, week_X.csv
    we literally have to scan entire directory for all the matching filenames. It would take a lot of time to create but easy to use with CSV
3) We can use arg parameters to take input
    Like: ```python run.py --database db.csv --register reg.csv --weeks Week_ ```

**Comment by sainikhileshreddy** [comment]
let me know if you find anything useful or have any new ways to implement using cli.

the core internal program is already done. Its just matter of adding support for csv. It might take few days as the complexity is growing.

**Comment by aravindvnair99** [comment]
@SaiNikhileshReddy Right now I am using the `assets` folder for the CI. It has dummy data. A user can fill that with actual data and pass the file as an argument through the CLI. That sounds best to me.

**Comment by sainikhileshreddy** [comment]
So, instead of long options from cli arg right

**Comment by sainikhileshreddy** [comment]
like ```python run.py --directory=assets```

**Comment by aravindvnair99** [comment]
> like `python run.py --directory=assets`

@SaiNikhileshReddy Instead of that, let it be as it is now. No change for that. There should be an internal logic to accept CSV / XLSX. Irrespective of the file passed, the program should continue.

**Comment by sainikhileshreddy** [comment]
So, It should take assets as default location to check if input arguments are not present for csv data.

**Comment by aravindvnair99** [comment]
>    Like: `python run.py --database db.csv --register reg.csv --weeks Week_ `

@SaiNikhileshReddy We could go with this. When we run the program, we provide the options in whatever order. And the program takes those files and continues. The only change now is accepting CSV as input as well and not just XLSX. No other change.

**Comment by sainikhileshreddy** [comment]
If that's the case then some old code has to be changed. I can complete it in few more days.

**Comment by sainikhileshreddy** [comment]
Do you have anymore additional features that would make it complete?

**Comment by aravindvnair99** [comment]
@SaiNikhileshReddy Right now with respect to #4, my only suggestion is:

The current implementation only allows XLSX:
```console
python run.py db.xlsx ws.xlsx
```
Proposed implementation:
- Being able to input CSV files
```console
python run.py db.csv ws.csv
```
- While also being able to continue providing input as XLSX
```console
python run.py db.xlsx ws.xlsx
```

Steps:

- Detect the file type
- Parse accordingly
- If the input was XLSX, output as XLSX
- If the input was CSV, output as CSV

For more feature requests, we can create additional issues as necessary.

**Comment by aravindvnair99** [comment]
@SaiNikhileshReddy Also, before you proceed, I think we should merge #2 first. Can you fix this: https://github.com/DSC-ASEB/Weekly-Shuffle-Partner-Generator/pull/2#issuecomment-812907907 so that I can merge it in? Just that one issue is pending in that PR.

**Comment by sainikhileshreddy** [comment]
@aravindvnair99 , There is even Weeks data right. If we are using csv then it would be hard to know the format for weeks and location of them.

**Comment by aravindvnair99** [comment]
> @aravindvnair99 , There is even Weeks data right. If we are using csv then it would be hard to know the format for weeks and location of them.

@SaiNikhileshReddy No, it will be one format itself. Oh, that reminds me of something. CSV is a table in simple terms. So, for multiple weeks, it would be individual CSV files. I don't think it will be a valid use case then as let's say we have 20 weeks. That would mean 20 different files.

With that said, I guess this issue can be closed. We can restrict to XLSX as input and output as CSV or XSLX.

**Comment by sainikhileshreddy** [comment]
Oh yeah. That just adds unnecessary complexity.

**Comment by aravindvnair99** [comment]
Closing this issue.
